/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vango2.View;

import Classe.Cadastro;
import Coneccao.AlunoDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JInternalFrame;
import java.sql.ResultSet;
import java.sql.SQLException;
import Coneccao.MororistaDao;
import Classe.Motorista;
import Coneccao.MororistaDao;
import javax.swing.JOptionPane;
import Servico.MotoristaServico;
import Classe.Motorista;


/**
 *
 * @author User
 */
public class CadastroMotorista extends javax.swing.JFrame {

    private Cadastro cadastro;
    private Motorista motorista;
    private int codMorista = 0;
    private MotoristaServico servico;

    /**
     * Creates new form CadastroAluno
     */
    public CadastroMotorista() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public CadastroMotorista(int cod) {
                                                           
        if(this.codMorista == 0){
            this.setTitle("Cadastro de Aluno");
        }else{
            this.setTitle("Alteração de Aluno");
            var a = servico.consultarMotorista(this.codMorista);
            txtCnh.setText(a.getCnh());
            txtModeloVan.setText(a.getModeloVan());
            txtAsssentosVan.setText(String.valueOf(a.getAssentos()));
            txtValorMedioCobrado.setText(String.valueOf(a.getValorAcobrar()));
            
        }
        
        setLocationRelativeTo(null);

    }

    private boolean camposPreenchidos() {
        return !txtCnh.getText().isEmpty() && !txtModeloVan.getText().isEmpty()
                && !txtPlaca.getText().isEmpty() && !txtAsssentosVan.getText().isEmpty()
                && !txtValorMedioCobrado.getText().isEmpty();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCnh = new javax.swing.JTextField();
        txtModeloVan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAsssentosVan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtValorMedioCobrado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtUnip = new javax.swing.JRadioButton();
        txtFacens = new javax.swing.JRadioButton();
        txtUniso = new javax.swing.JRadioButton();
        txtAnhaguera = new javax.swing.JRadioButton();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Design sem nome.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(900, 700));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setText("Cadastro Motorista");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 110, 362, 54);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("CNH:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 200, 44, 34);

        txtCnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnhActionPerformed(evt);
            }
        });
        jPanel1.add(txtCnh);
        txtCnh.setBounds(380, 200, 143, 34);

        txtModeloVan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloVanActionPerformed(evt);
            }
        });
        jPanel1.add(txtModeloVan);
        txtModeloVan.setBounds(380, 290, 143, 34);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Valor médio cobrado :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 410, 180, 30);

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPlaca);
        txtPlaca.setBounds(380, 330, 143, 34);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Placa :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(330, 330, 80, 25);

        txtAsssentosVan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAsssentosVanActionPerformed(evt);
            }
        });
        jPanel1.add(txtAsssentosVan);
        txtAsssentosVan.setBounds(380, 370, 143, 34);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Proximo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 490, 103, 33);

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(410, 540, 80, 23);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Instituições que atende :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 240, 200, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Assentos na Van :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(240, 370, 140, 25);

        txtValorMedioCobrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorMedioCobradoActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorMedioCobrado);
        txtValorMedioCobrado.setBounds(380, 410, 143, 34);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Modelo da van :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(250, 290, 140, 25);

        txtUnip.setText("Unip");
        jPanel1.add(txtUnip);
        txtUnip.setBounds(390, 250, 48, 21);

        txtFacens.setText("Facens");
        txtFacens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacensActionPerformed(evt);
            }
        });
        jPanel1.add(txtFacens);
        txtFacens.setBounds(440, 250, 60, 21);

        txtUniso.setText("Uniso");
        jPanel1.add(txtUniso);
        txtUniso.setBounds(510, 250, 53, 21);

        txtAnhaguera.setText("Anhaguera");
        jPanel1.add(txtAnhaguera);
        txtAnhaguera.setBounds(580, 250, 90, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnhActionPerformed

    private void txtModeloVanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloVanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloVanActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtAsssentosVanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsssentosVanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsssentosVanActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MororistaDao as = new MororistaDao();

        new CadastroM2(as.maiorValor(cadastro)).setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Motorista motorista;
        if (camposPreenchidos()) {

            MororistaDao as = new MororistaDao();
            this.servico = new MotoristaServico();
            String assentosTexto = txtAsssentosVan.getText();

// Convertendo o valor de texto para inteiro
            int assentos = Integer.parseInt(assentosTexto);
            String valorMedioCobradoTexto = txtValorMedioCobrado.getText();

// Tentando converter o valor de texto para double
            double valorMedioCobrado;

            try {
                valorMedioCobrado = Double.parseDouble(valorMedioCobradoTexto);
            } catch (NumberFormatException e) {
                // Lidando com o caso em que o valor não é um número válido
                // Aqui você pode exibir uma mensagem de erro, definir um valor padrão, etc.
                System.out.println("Erro ao converter o valor médio cobrado para double. Usando valor padrão.");
                valorMedioCobrado = 0.0; // Defina um valor padrão ou trate de acordo com a sua lógica
            }

            motorista = new Motorista(this.codMorista, txtCnh.getText(), txtModeloVan.getText(), txtPlaca.getText(), assentos, valorMedioCobrado, as.maiorValor(cadastro));
            servico.inserirMotorista(motorista);
            new CadastroFinalMotorista().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.", "Campos obrigatórios", JOptionPane.WARNING_MESSAGE);

        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtValorMedioCobradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorMedioCobradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorMedioCobradoActionPerformed

    private void txtFacensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton txtAnhaguera;
    private javax.swing.JTextField txtAsssentosVan;
    private javax.swing.JTextField txtCnh;
    private javax.swing.JRadioButton txtFacens;
    private javax.swing.JTextField txtModeloVan;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JRadioButton txtUnip;
    private javax.swing.JRadioButton txtUniso;
    private javax.swing.JTextField txtValorMedioCobrado;
    // End of variables declaration//GEN-END:variables
}
